# Generated by Django 4.2.2 on 2023-06-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_commentphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentphone',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
