# Generated by Django 4.1.5 on 2023-06-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_customer_email_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='title',
        ),
    ]
