# Generated by Django 4.2.2 on 2023-06-26 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commentphone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentPhone',
            new_name='CommentPost',
        ),
    ]
